// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOzmI3_TIl1WlnaM9F_bAWpUqo6g_P_tY',
    appId: '1:793772656637:web:7615334bb5352b1746bb94',
    messagingSenderId: '793772656637',
    projectId: 'flutter-pushnotification-6b34a',
    authDomain: 'flutter-pushnotification-6b34a.firebaseapp.com',
    storageBucket: 'flutter-pushnotification-6b34a.firebasestorage.app',
    measurementId: 'G-SCBF0NJQ57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtBZ6II5y2vt7y-6o-hBi3WJMMV9H3k8',
    appId: '1:793772656637:android:ed010c173fd471b846bb94',
    messagingSenderId: '793772656637',
    projectId: 'flutter-pushnotification-6b34a',
    storageBucket: 'flutter-pushnotification-6b34a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWx5plic4rjcbI4TRSdvkXW2W69AnOTzg',
    appId: '1:793772656637:ios:ef64ab0ff6e5d4be46bb94',
    messagingSenderId: '793772656637',
    projectId: 'flutter-pushnotification-6b34a',
    storageBucket: 'flutter-pushnotification-6b34a.firebasestorage.app',
    iosBundleId: 'com.example.docchakravue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWx5plic4rjcbI4TRSdvkXW2W69AnOTzg',
    appId: '1:793772656637:ios:ef64ab0ff6e5d4be46bb94',
    messagingSenderId: '793772656637',
    projectId: 'flutter-pushnotification-6b34a',
    storageBucket: 'flutter-pushnotification-6b34a.firebasestorage.app',
    iosBundleId: 'com.example.docchakravue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOzmI3_TIl1WlnaM9F_bAWpUqo6g_P_tY',
    appId: '1:793772656637:web:ce266d8d7dc935f146bb94',
    messagingSenderId: '793772656637',
    projectId: 'flutter-pushnotification-6b34a',
    authDomain: 'flutter-pushnotification-6b34a.firebaseapp.com',
    storageBucket: 'flutter-pushnotification-6b34a.firebasestorage.app',
    measurementId: 'G-CCMNDFNKJ4',
  );

}